---

- name: NGINX TEMPLATE | Setting the php-fpm fastcgi server of nginx
  template:
    src: templates/php-fpm.conf.j2
    dest: /etc/nginx/conf.d/php-fpm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: NGINX TEMPLATE | Setting the php-fpm fastcgi server of nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx