---

- debug: msg="==> Setting phg-fpm system"

# Setting  PHP7.
- name: PHP-FPM | create socket directory for CentOS 7
  file: path=/run/php-fpm/ state=directory mode=0755
  when: ansible_distribution_major_version == "7"

# setting the php.ini .
- name: PHP-INI | Set the php.ini
  template:
    src: templates/php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 644
  notify: restart php-fpm

# setting the www.conf .
- name: PHP-FPM | Disable port listen
  lineinfile: >
    dest=/etc/php-fpm.d/www.conf
    regexp='^;?listen = 127.0.0.1:9000'
    line=';listen = 127.0.0.1:9000'
    state=present
  notify: restart php-fpm

- name: PHP-FPM | Enable socket listen
  lineinfile: >
    dest=/etc/php-fpm.d/www.conf
    regexp='^;?listen = /run/php-fpm/www.sock'
    line='listen = {{ centos_php_fastcgi_listen }}'
    state=present
  notify: restart php-fpm

- name: PHP-FPM | Set permissions on socket - owner
  lineinfile: >
    dest=/etc/php-fpm.d/www.conf
    regexp='^;?listen.owner'
    line='listen.owner = {{ php_owner }}'
    state=present
  notify: restart php-fpm

- name: PHP-FPM | Set permissions on socket - group
  lineinfile: >
    dest=/etc/php-fpm.d/www.conf
    regexp='^;?listen.group'
    line='listen.group = {{ php_group }}'
    state=present
  notify: restart php-fpm

- name: PHP-FPM | Set permissions on socket - mode
  lineinfile: >
    dest=/etc/php-fpm.d/www.conf
    regexp='^;?listen.mode'
    line='listen.mode = 0660'
    state=present
  notify: restart php-fpm